name: Deploy Java App to EC2

on:
  push:
    branches: [ "main" ]   # change if default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: 98.80.120.96
      EC2_USER: ec2-user
      EC2_SSH_KEY: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEAwnyqj9nwqCkKK7m1d6n2XIBYtUdsuVVCqFt9E96omfFLEsN6
            Ixfr4L/oIp/xPF9d+YFfT7BL+77l9jXHPx/sek3EmvwGy4hMbLos9s2XqYebvUQm
            Uwwp4NOD7VIY0gHRyLKQqDZBvnzPNr0IaVXGtMvxr08RJtNOjRrJVBn2bvvIMHRL
            CUYIPhXVa8lwY0v+GYpYmYCbFYrUNMOvAbL122WigrSM2XYn2TbBOSHG+ZUiCty1
            kY4Veul3wXMRwxnvJdx1UAJaszArj8UxEBUoh+JUOTnJOfjlrvOIOH6a6+rg2jeb
            3Tdvw9zhgH1/pLn2d7xBR3oxgMyykjp6uZhNBQIDAQABAoIBAGVgOEPNdW0iH0QV
            hCrA9ELZP+QWO+0LLTi2n6boy/eaV+iK7jI2uOQpBCZwOn2etExnDDhsi97IbfP9
            qkMUL968hLvInP4gqL2P+foXxnM+1YY9bMCjOX0Qo9bjkT5+Zkx4D4Eu7uwNALHm
            rOjDJlV9bRhVXXpgcLSKfuEQu2yzdrbXKjKjvBF4ar3OjzvO346d1KLUX5uEGqVP
            3bDuABInsddS+kpR+nRltO6PkKsBEUvPV1CHSiwFMC6wotBCQLzfnDLlMhRHHpC6
            SgMf4BMT7OpNTnRvSS4iwA22s+KDPF9g/NFcYee4NvtguSecXbbtvHI2ppu28rXU
            oWnShc0CgYEA5gpwFwAB0RLVewAmGO4gc4Kz4+rWCGfYelh22drDVvUngnhxnxwn
            Rk9VY1v8HNrYi8R77jSe7IoS46rewoiU3LId15PADiawy9HTXbyWPaz8Vmw/OnoL
            MtWrTg4pfUFvDIi8hvWLGTdgJhg7JdMzmK4IAD9n6QWUGhzpMD4tl58CgYEA2G8g
            yOl4YgZx8F1f9qQS4jRbbRYD1HBDff4+aCO1XOgeL6KCZ7VY+h2oyuQXHA+Z1d6J
            lQ6pwsvWhkUzTekTSMolnp+VklvSsVCDDV76MOTGgIIPcAELkJdC3DIPgBUCSzKD
            YD8NBdDiJkvSaubwSHcpotXLP+IQRH2Q2FihaNsCgYAx8CQjKhI6497KI98hXFhZ
            Gw+YM7ug+YIqFRg/9NihAPlBvonT45W3ErPTrP1O+kc2GEJbFLtHWDX/jHFtQ58l
            Rdlqmh2ANO/+Xx+GYtEutGXXEQqs1B+oOnBEsphZI6JK00gx+A3pPHc37dyxOmci
            Bu2fuCQDlv1uqcYJfgYBuwKBgC8bQM95wTHUpUfjitdrrpB9RMjhWcQLCyWJCJwx
            6W9nNeq4PBnGZq9JdUtziXQaESlzXg6LOnejVfWzag8zA3d8R+PWZ/+K7LibBWsL
            mPi7Ulj19dYy5Al8Ypj6bFU8PVuQivePwY3agN5E8m9CBFpBVVaTocEtusytZ7Eu
            2TKxAoGBAKIPkxOfmX6iYUMdxPy+N798etV7lGSDjC0P+wcj59UwMeRqava4UhU4
            8/xM2n6hzVhIfKB0DCshMNPx69CxWLQ8UB8fhAKVWeYBjNxs3tWfVUofzePbbMtk
            vcD9o2s13/h4q4wFU93uEAymDaAbnZ558hmc1MZ3f0bu9hyevS4S
            -----END RSA PRIVATE KEY-----

    steps:
     # 0️⃣ Delete old code except backup and deploy.sh
      - name: Clean old code on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/cartechindia
            echo "🧹 Deleting all previous code except deploy.sh and backup..."
            find . -mindepth 1 -maxdepth 1 ! -name 'deploy.sh' ! -name 'backup' -exec rm -rf {} +
            echo "✅ Old code deleted."
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v1.0.0

      # 2️⃣ Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build the Java app (skip tests)
      - name: Build Java app
        run: mvn clean package -DskipTests

      # 4️⃣ Copy JAR to EC2 (hardcoded name)
      - name: Copy cartechindia.jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_SSH_KEY }}
          source: "target/cartechindia-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/cartechindia/cartechindia.jar"

      # 5️⃣ Run deploy.sh on EC2
      - name: Run deploy script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/cartechindia
            chmod +x deploy.sh
            ./deploy.sh
